# Generated by Django 2.2.5 on 2019-10-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Age'),
        ),
    ]
