# Generated by Django 2.2.5 on 2019-10-10 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_user_profile_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
    ]
