# Generated by Django 2.2.5 on 2019-10-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20191010_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='session_time',
        ),
    ]
