# Generated by Django 2.2.6 on 2019-10-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_remove_user_profile_session_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='phone_number',
            field=models.CharField(default='', max_length=12),
        ),
    ]
