# Generated by Django 2.2.6 on 2019-11-04 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_remove_user_profile_time_last_logout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
